### ISSUE TITLE
Support for customizing time zone in config

### ISSUE THREAD

**Issue by rh12503** [rborsetti/discordhypixeltracker#1]
Currently, the project only supports UTC time zones. However, this can be problematic for users who operate in different time zones. Therefore, we suggest adding support for customizable time zones in the project config.

Not all users of the project are based in the UTC time zone, and some may find it difficult to work with time data that is not in their local time zone. It is important to offer flexibility and cater to the needs of all users, regardless of their geographical location. By adding support for customizable time zones, users can configure the project to display time data in their local time zone, making it easier for them to work with.

1. The world has 24 different time zones, with UTC being one of them.
2. UTC is not necessarily the default time zone for all users of the project.
3. Customizable time zones are a common feature in many projects and applications, allowing users to work with time data in their local time zone.

_ChatGPT, 2023_

**Comment by rborsetti** [comment]
I'll look into it now

**Comment by rborsetti** [comment]
https://www.reddit.com/r/discordapp/comments/ofsm4e/dynamic_timestamps/

I've implemented this, should do the trick.

**Comment by rh12503** [comment]
Wow, what a great addition!
